Numpy is the fundamental package for scientific computing with Python. It contains among other things:
- a powerful N-dimentsional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

You already downloaded Numpy by installing the Anaconda(numpy, pandas 패키지가 들어있음 ) 

In [1]:
import numpy as np
# import numpy
# funcion of numpy can be used by typing "numpy.func_name()" ex) numpy.array
# as np: represents the alias(별명) of numpy
# you can use 'np.funcion_name' instead of using 'numpy.func_name()'
# np.funcion_name' 사용 가능 

## How to create numpy arrays

In [2]:
### sequence data

In [3]:
np.array([0.0,1.2,3.4,5.6]) # .array = function (list or dict or tuple)

array([0. , 1.2, 3.4, 5.6])

In [4]:
obj=np.array([0.0,1.2,3.4,5.6])

In [5]:
# type of elements in obj is integer
# obj 에 있는 값들은 모두 정수형이다. 

In [6]:
obj.dtype # dtype is a property(특성) of object 

dtype('float64')

In [7]:
obj.dtype

dtype('float64')

In [7]:
type(obj) 
# ndarray means 'N-dimensioanl Array' = support computation of multidimentional matrix(array)

numpy.ndarray

In [9]:
### matrix

In [94]:
np.array([[1,2,3],[4,5,6],[7,8,9]]) # 3-by-3 array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
np[0][1]

TypeError: 'module' object is not subscriptable

## arange: similar with range / array with range 범위와 같이 있는 어레이 만드는 거

In [15]:
np.arange(1,10).reshape(3,3) # 맨 마지막 숫자는 포함안함 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(5) # = array([0,1,2,3,4])

array([0, 1, 2, 3, 4])

In [10]:
np.arange(4)

array([0, 1, 2, 3])

In [17]:
# np.arange(start, end, step_size)

In [82]:
np.arange(1,6,2) # 1-by-3

array([1, 3, 5])

In [83]:
np.arange(1,6,2).shape

(3,)

In [84]:
np.arange(3,10,3).reshape(3,1).shape # 3행 1열 

(3, 1)

In [20]:
# reshape the array
np.arange(1,6,2).reshape(3,1) # 3-by-1

array([[1],
       [3],
       [5]])

In [22]:
# to check the dim of the array
np.arange(1,6,2).reshape(3,1).shape

(3, 1)

In [15]:
np.arange(1,6,2).reshape(3,1).shape

(3, 1)

In [16]:
np.arange(1,6,2).shape

(3,)

In [87]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
np.arange(10).reshape(2,5).shape

(2, 5)

In [32]:
np.arange(10).reshape(5,2).shape

(5, 2)

In [33]:
np.arange(10).reshape(5,2) # 오른쪽으로 아래로 

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### What if we want to generate an array with real number? 
실제 숫자로 어레이를 생성하려면 어떻게 해야 하는가?

In [34]:
# np.linspace

In [89]:
np.linspace(0,np.pi,100) # start, end, number of elements in ndarray

array([0.        , 0.03173326, 0.06346652, 0.09519978, 0.12693304,
       0.1586663 , 0.19039955, 0.22213281, 0.25386607, 0.28559933,
       0.31733259, 0.34906585, 0.38079911, 0.41253237, 0.44426563,
       0.47599889, 0.50773215, 0.53946541, 0.57119866, 0.60293192,
       0.63466518, 0.66639844, 0.6981317 , 0.72986496, 0.76159822,
       0.79333148, 0.82506474, 0.856798  , 0.88853126, 0.92026451,
       0.95199777, 0.98373103, 1.01546429, 1.04719755, 1.07893081,
       1.11066407, 1.14239733, 1.17413059, 1.20586385, 1.23759711,
       1.26933037, 1.30106362, 1.33279688, 1.36453014, 1.3962634 ,
       1.42799666, 1.45972992, 1.49146318, 1.52319644, 1.5549297 ,
       1.58666296, 1.61839622, 1.65012947, 1.68186273, 1.71359599,
       1.74532925, 1.77706251, 1.80879577, 1.84052903, 1.87226229,
       1.90399555, 1.93572881, 1.96746207, 1.99919533, 2.03092858,
       2.06266184, 2.0943951 , 2.12612836, 2.15786162, 2.18959488,
       2.22132814, 2.2530614 , 2.28479466, 2.31652792, 2.34826

In [36]:
np.linspace(0,np.pi,100).shape # 100개의 값이 들어간다. 

(100,)

In [24]:
np.linspace(0,np.pi,10).shape

(10,)

In [93]:
np.linspace(0,np.pi,100).reshape(10,10)

array([[0.        , 0.03173326, 0.06346652, 0.09519978, 0.12693304,
        0.1586663 , 0.19039955, 0.22213281, 0.25386607, 0.28559933],
       [0.31733259, 0.34906585, 0.38079911, 0.41253237, 0.44426563,
        0.47599889, 0.50773215, 0.53946541, 0.57119866, 0.60293192],
       [0.63466518, 0.66639844, 0.6981317 , 0.72986496, 0.76159822,
        0.79333148, 0.82506474, 0.856798  , 0.88853126, 0.92026451],
       [0.95199777, 0.98373103, 1.01546429, 1.04719755, 1.07893081,
        1.11066407, 1.14239733, 1.17413059, 1.20586385, 1.23759711],
       [1.26933037, 1.30106362, 1.33279688, 1.36453014, 1.3962634 ,
        1.42799666, 1.45972992, 1.49146318, 1.52319644, 1.5549297 ],
       [1.58666296, 1.61839622, 1.65012947, 1.68186273, 1.71359599,
        1.74532925, 1.77706251, 1.80879577, 1.84052903, 1.87226229],
       [1.90399555, 1.93572881, 1.96746207, 1.99919533, 2.03092858,
        2.06266184, 2.0943951 , 2.12612836, 2.15786162, 2.18959488],
       [2.22132814, 2.2530614 , 2.2847946

### zero matrix 

In [41]:
np.zeros(10).reshape(2,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### one matrix

In [42]:
np.ones(10).reshape(10,1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

### identify matrix (단위행렬)
주대각선 원소가 1이고 나머지는 0인 경우

In [43]:
np.eye(5) # 5 = # of diagonal elements in the identify matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## changing the type of data: convert the type of the ndarray data

In [32]:
string=np.array(["1.5",'0.62','2','3.14']) # all the elements of ndrray are string

In [48]:
# how can we convert the string to float? 문자를 실수형으로 바꾸는 방법 
number=string.astype(float)

In [33]:
number=string.astype(float)

In [34]:
number

array([1.5 , 0.62, 2.  , 3.14])

In [47]:
## object_name.astype(data_type) - > you can chance the type of data

In [49]:
number.dtype

dtype('float64')

In [35]:
string.dtype # 4글자 유니코드 문자열

dtype('<U4')

In [52]:
string2=np.array(['1','0','2','3']) # all the elemetns of ndrray are string

In [36]:
string2 = np.array(['1','0','2','3']) # 값을 리스트 처럼 넣어주네 

In [37]:
string2

array(['1', '0', '2', '3'], dtype='<U1')

In [38]:
integer=string2.astype(int)

In [39]:
integer.dtype

dtype('int32')

- create ndarray in numpy
- reshape ndarray
- zero vector, one vector, and and identity matrix

## esc -> m: you can use markdown

## random number generation in numpy 

In [2]:
## When you learn ML algorithm or regression methods, the best way is simulation 
## 머신러닝할 때 가장 익히기 좋은 방법은 랜덤값을 만들어서 시뮬레이션 해보는 것이다. 

In [3]:
## you need to generate random numbers..

In [4]:
# rand: generate a number whose range is (0,1) : 0과 1사이의 값을 생성한다. 
# randint: generate integer.. : 정수형을 생성한다. 

In [40]:
import numpy as np

### rand():  0과 1사이의 값을 생성한다. 

In [7]:
np.random.rand() 
# if I do not put anything in the pranthesis, python generate a single number..
# 괄호 안에 아무값도 넣어주지 않으면 하나의 숫자만 생성한다. 

0.1839440152408518

In [8]:
# np.random.rand([decide the dimension of random number]) 
# 몇 행 몇 열로 할 것인지 정하는 것은 괄호 안에 [] 안에 넣어준다. 

In [41]:
np.random.rand(3) # generate 1-by-3 vector 

array([0.55440735, 0.04496167, 0.96832063])

In [45]:
a = np.random.rand(3)

In [74]:
a.reshape(1,-1)

array([[0.62915097, 0.61371333, 0.99915091]])

In [51]:
np.random.rand(3,2) # generate 3-by-2 matrix

array([[0.56244814, 0.46110473],
       [0.9813512 , 0.43744982],
       [0.09694204, 0.84497231]])

In [57]:
b =np.random.rand(3,2,3) # 3-by-2-by-3 3차원으로 만듬 

In [59]:
b

array([[[0.94743984, 0.03868542, 0.00274779],
        [0.45080156, 0.79242161, 0.92698778]],

       [[0.90550778, 0.6355895 , 0.29252534],
        [0.00396229, 0.62917204, 0.67126359]],

       [[0.22258287, 0.13848557, 0.54366694],
        [0.225156  , 0.23193523, 0.34050586]]])

In [60]:
b[0][0][0]

0.9474398361859585

### randint() : 난수인데 정수형을 생성한다. 

In [13]:
## np.rnadom.randint([lower,upper,size])

In [14]:
np.random.randint(0,10,size=(3,4)) # 3-by-4 matrix

array([[1, 0, 3, 8],
       [8, 6, 9, 8],
       [3, 8, 0, 1]])

In [70]:
np.random.randint(0,10,size=4) # single number 한개의 숫자만 나옴 

array([5, 0, 9, 7])

### operation/ math, algebra 

In [17]:
# summation 더하기 
arr1 = np.array([0,1,3])
arr2 = np.array([2,4,5])

In [18]:
arr1+arr2 # elementwise summation: 각 element 끼리 더해짐 

array([2, 5, 8])

In [19]:
arr1-arr2  # elementwise substraction

array([-2, -3, -2])

In [20]:
arr1*arr2  # elementwise multiplication

array([ 0,  4, 15])

In [21]:
arr1*2 # multipy a scalar: 값을 곱해줌 

array([0, 2, 6])

In [22]:
arr1**2 # power of elements: 값을 제곱해줌 

array([0, 1, 9], dtype=int32)

In [23]:
# logical operation
arr1>2

array([False, False,  True])

### descriptive statistics of the elements

In [24]:
arr1.mean()

1.3333333333333333

In [25]:
arr1.sum()

4

In [26]:
arr1.std()

1.247219128924647

In [29]:
[arr1.min(),arr1.max()]

[0, 3]

### computation of matrix

1. dot projuct
2. transpose
3. inverse matrix
4. determinant
5. etc..

In [30]:
# dot product: 벡터의 내적 

In [32]:
mat1=np.arange(4).reshape(2,2)

In [33]:
mat1

array([[0, 1],
       [2, 3]])

In [34]:
mat2=np.arange(5,9).reshape(2,2)

In [35]:
mat2

array([[5, 6],
       [7, 8]])

In [36]:
mat1.dot(mat2) # A.dot(B) = np.dot(A,B)

array([[ 7,  8],
       [31, 36]])

In [37]:
np.dot(mat1,mat2) # 두 행렬 곱해줌 

array([[ 7,  8],
       [31, 36]])

In [38]:
# transpose: 전치 행렬 

In [39]:
np.transpose(mat1) # 전치 행렬

array([[0, 2],
       [1, 3]])

In [40]:
# inverse: 역함수 

In [41]:
np.linalg.inv(mat1) # 역함수

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [42]:
# det

In [43]:
np.linalg.det(mat1) # 행렬값

-2.0

## index and slicing of ndarray

In [76]:
a1=np.arange(10)

In [77]:
a1[0] # indexing

0

In [78]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a1[4]

4

In [49]:
a1[5]=70 # updating an element: 값 업데이트 해주기 

In [50]:
a1

array([ 0,  1,  2,  3,  4, 70,  6,  7,  8,  9])

In [51]:
a1[[0,3,5]] # array_name[[loc1,loc2,loc3...]]: 위치로 값 찾아내기 [[]]이거 두개 써줌 

array([ 0,  3, 70])

In [54]:
# index of matrix: 행렬에서 값 찾기 

In [80]:
a2=a1.reshape(5,2)

In [56]:
a2 

array([[ 0,  1],
       [ 2,  3],
       [ 4, 70],
       [ 6,  7],
       [ 8,  9]])

In [57]:
# a2[row_num,col_num]

In [58]:
a2[2,1]

70

In [81]:
a2[3,0]

6

In [59]:
a2[2] # print the 3rd row

array([ 4, 70])

In [60]:
# update a number
a2[2,1] = 80

In [61]:
a2

array([[ 0,  1],
       [ 2,  3],
       [ 4, 80],
       [ 6,  7],
       [ 8,  9]])

In [62]:
a2[0]=np.array([1,3])

In [63]:
a2

array([[ 1,  3],
       [ 2,  3],
       [ 4, 80],
       [ 6,  7],
       [ 8,  9]])

In [64]:
# you can print multiple number in a matrix

### array_name[[row_numbers],[column_names]]

In [66]:
a2[[1,4],[0,1]]

array([2, 9])

In [68]:
a2[[1,4],[0,1]]

array([2, 9])

### indexing using a condition 

In [69]:
a1>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [70]:
# print only the numbers that satisfies the condition

In [72]:
a1[a1>3]

array([ 4, 80,  6,  7,  8,  9])

In [73]:
a1

array([ 1,  3,  2,  3,  4, 80,  6,  7,  8,  9])

## slicing

In [74]:
# slicing a sequence

In [96]:
seq1=np.arange(20)

In [97]:
seq1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [98]:
seq1[4:11] # array_name[starting_loc:ending_loc]

array([ 4,  5,  6,  7,  8,  9, 10])

In [99]:
mat3=seq1.reshape(5,4)

In [105]:
mat3[1:2,:]]

SyntaxError: invalid syntax (<ipython-input-105-266ccb2c365f>, line 1)

In [102]:
mat3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

### mat3[row_name,column_name]

In [86]:
mat3[2:4,1:3]

array([[ 9, 10],
       [13, 14]])